// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommentAttachment struct {
	ID        string
	CommentID string
	UserID    string
	FileName  string
	FilePath  string
	FileSize  int64
	MimeType  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Label struct {
	ID             string
	Name           string
	Color          string
	ProjectID      string
	OrganizationID string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Organization struct {
	ID        string
	UserID    string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type OrganizationUser struct {
	ID             string
	OrganizationID string
	UserID         string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Project struct {
	ID             string
	UserID         string
	OrganizationID string
	Name           string
	KeyPrefix      string
	Type           string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ProjectsUser struct {
	ID        string
	ProjectID string
	UserID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Role struct {
	ID             string
	OrganizationID string
	DefaultID      *string
	Name           string
	Description    string
	Permissions    []string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RolesProject struct {
	ID        string
	RoleID    string
	ProjectID string
	UserID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Session struct {
	ID           string
	UserID       string
	AccessToken  string
	RefreshToken string
	ExpiresAt    int64
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Status struct {
	ID             string
	Name           string
	Color          string
	ProjectID      string
	OrganizationID string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Task struct {
	ID             string
	Title          string
	Description    *string
	UserID         string
	AssignerID     *string
	ReporterID     *string
	OrganizationID string
	ProjectID      string
	StatusID       string
	Priority       int16
	DueDate        pgtype.Timestamp
	OrderIndex     *int32
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type TaskAssignee struct {
	ID        string
	TaskID    string
	UserID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TaskAttachment struct {
	ID        string
	TaskID    string
	UserID    string
	FileName  string
	FilePath  string
	FileSize  int64
	MimeType  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TaskComment struct {
	ID              string
	TaskID          string
	UserID          string
	ParentCommentID *string
	Comment         string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type TaskLabel struct {
	ID        string
	TaskID    string
	LabelID   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
