// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        string
	UserID    string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Project struct {
	ID             string
	UserID         string
	OrganizationID string
	Name           string
	KeyPrefix      string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ProjectsUser struct {
	ID        string
	ProjectID string
	UserID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Role struct {
	ID             string
	OrganizationID string
	DefaultID      pgtype.Text
	Name           string
	Description    string
	Permissions    []string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RolesProject struct {
	ID        string
	RoleID    string
	ProjectID string
	UserID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Session struct {
	ID           string
	UserID       string
	AccessToken  string
	RefreshToken string
	ExpiresAt    int64
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
