// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: status.sql

package db

import (
	"context"
)

const createStatus = `-- name: CreateStatus :one
INSERT INTO status (
  name, color, project_id, organization_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, color, project_id, organization_id, created_at, updated_at
`

type CreateStatusParams struct {
	Name           string
	Color          string
	ProjectID      string
	OrganizationID string
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, createStatus,
		arg.Name,
		arg.Color,
		arg.ProjectID,
		arg.OrganizationID,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.ProjectID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM status
WHERE id = $1 AND project_id = $2 AND organization_id = $3
`

type DeleteStatusParams struct {
	ID             string
	ProjectID      string
	OrganizationID string
}

func (q *Queries) DeleteStatus(ctx context.Context, arg DeleteStatusParams) error {
	_, err := q.db.Exec(ctx, deleteStatus, arg.ID, arg.ProjectID, arg.OrganizationID)
	return err
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, color, project_id, organization_id, created_at, updated_at FROM status
WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id string) (Status, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.ProjectID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatuses = `-- name: GetStatuses :many
SELECT id, name, color, project_id, organization_id, created_at, updated_at FROM status
WHERE project_id = $1 AND organization_id = $2
`

type GetStatusesParams struct {
	ProjectID      string
	OrganizationID string
}

func (q *Queries) GetStatuses(ctx context.Context, arg GetStatusesParams) ([]Status, error) {
	rows, err := q.db.Query(ctx, getStatuses, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.ProjectID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE status
SET name = $2, color = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, color, project_id, organization_id, created_at, updated_at
`

type UpdateStatusParams struct {
	ID    string
	Name  string
	Color string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, updateStatus, arg.ID, arg.Name, arg.Color)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.ProjectID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
